# Generated by Django 3.2.9 on 2021-12-10 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('desc', models.CharField(default='', max_length=256)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=64)),
                ('addr', models.CharField(default='', max_length=64)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(default='')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
            ],
        ),
    ]
